"""HealthData.gov config-driven ingestion.

``component.py`` defines one component:

* ``HealthDataGovDataset`` — **one instance per dataset**, under
  ``datasets/<slug>/defs.yaml`` (generated by
  ``data/scripts/scrape_healthdata_gov.py``). Each emits a catalog ``AssetSpec``
  under the ``sources/`` prefix and, when ``enabled``, a ``dlt``-backed table
  asset under the ``ingestion/`` prefix, downstream of it.

The three cadence asset jobs + schedules need no per-instance config, so they
are plain code, not a component — see
``ohdp_orchestration.jobs.healthdata_gov`` /
``ohdp_orchestration.schedules.healthdata_gov``.
"""
