"""HealthData.gov config-driven ingestion.

``component.py`` defines two components:

* ``HealthDataGovDataset`` — **one instance per dataset**, under
  ``datasets/<slug>/defs.yaml`` (generated by
  ``data/scripts/scrape_healthdata_gov.py``). Each emits a catalog ``AssetSpec``
  under the ``sources/`` prefix and, when ``enabled``, a ``dlt``-backed table
  asset under the ``ingestion/`` prefix, downstream of it.
* ``HealthDataGovCadenceSchedules`` — one instance (``schedules/defs.yaml``);
  three asset jobs + schedules, one per cadence, selecting table assets by tag.
"""
