"""The HealthData.gov binding of the shared Socrata dataset component.

One instance per dataset, under ``datasets/<slug>/defs.yaml`` (generated by
``data/scripts/scrape_socrata.py``). Everything this class does lives in
``ohdp_orchestration.components.socrata.SocrataDataset`` — see that module for
the asset shape. ADR-0008, ADR-0018.

The three cadence asset jobs + schedules are plain code, not a component —
see ``ohdp_orchestration.jobs.healthdata_gov`` /
``ohdp_orchestration.schedules.healthdata_gov``.
"""

from __future__ import annotations

from typing import ClassVar

from ohdp_ingestion.healthdata_gov import HEALTHDATA_GOV
from ohdp_ingestion.socrata import SocrataDomain
from ohdp_orchestration.components.socrata import SocrataDataset


class HealthDataGovDataset(SocrataDataset):
    """One HealthData.gov dataset. Schema == ``DatasetConfig`` + ``group_name``."""

    SOCRATA: ClassVar[SocrataDomain] = HEALTHDATA_GOV
