apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.store.name }}
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: {{ .Values.store.tokenSecretName }}
            namespace: {{ .Values.store.tokenNamespace }}
            key: {{ .Values.store.tokenSecretKey }}
