{{- range $es := .Values.externalSecrets }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $es.name }}
  namespace: {{ $es.namespace }}
spec:
  refreshInterval: {{ $.Values.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ $.Values.store.name }}
  target:
    name: {{ $es.name }}
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    {{- range $k, $remote := $es.keys }}
    - secretKey: {{ $k }}
      remoteRef:
        key: {{ $remote }}
    {{- end }}
---
{{- end }}
