#!/usr/bin/env python
"""One-time (re-runnable) scraper: HealthData.gov catalog -> per-dataset component.

    cd data && uv run python scripts/scrape_healthdata_gov.py --top-n 8

Walks the Socrata catalog API for healthdata.gov and writes one Dagster
**component instance** per dataset:

    ohdp_orchestration/defs/healthdata_gov/datasets/<slug>/defs.yaml

Each is an instance of ``HealthDataGovDataset`` (its ``attributes`` block is the
``DatasetConfig`` contract). The ``--top-n`` most-viewed datasets are written
``enabled: true``; the rest land disabled so the catalog is captured without
every dataset scheduling itself. Also regenerates the dbt sources file.

Re-running is safe: manual edits to ``enabled``, ``cadence``, ``row_limit`` and
``incremental_cursor`` are preserved; everything else refreshes from the live
catalog. Dataset directories that no longer match the catalog are removed.
"""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path
from typing import Any

import yaml

from ohdp_ingestion.healthdata_gov import iter_catalog
from ohdp_ingestion.healthdata_gov.config import DatasetConfig, slugify
from ohdp_ingestion.naming import database as ns_database
from ohdp_ingestion.naming import schema as ns_schema

_REPO = Path(__file__).resolve().parents[2]
_DEFS = _REPO / "data/src/ohdp_orchestration/defs/healthdata_gov"
_DEFAULT_OUT = _DEFS / "datasets"
_DBT_SOURCES = _REPO / "data/dbt/models/clean/healthdata_gov/_healthdata_gov__sources.yml"
# ADR-0013: RAW.healthdata_gov on Snowflake.
_RAW_DATABASE = ns_database("raw")
_RAW_SCHEMA = ns_schema("raw", "healthdata_gov")

_DATASET_TYPE = "ohdp_orchestration.defs.healthdata_gov.component.HealthDataGovDataset"

# Attributes a human may override in a generated file; never stomped on re-run.
_PRESERVE = ("enabled", "cadence", "row_limit", "incremental_cursor")


def _load_existing(out_dir: Path) -> dict[str, dict[str, Any]]:
    """id -> the `attributes` block of every existing dataset component."""
    existing: dict[str, dict[str, Any]] = {}
    for path in out_dir.glob("*/defs.yaml"):
        try:
            data = yaml.safe_load(path.read_text()) or {}
        except yaml.YAMLError:
            continue
        attrs = data.get("attributes") if isinstance(data, dict) else None
        if isinstance(attrs, dict) and attrs.get("id"):
            existing[attrs["id"]] = attrs
    return existing


def _dump_dataset(cfg: DatasetConfig) -> str:
    attributes = {
        "id": cfg.id,
        "name": cfg.name,
        "publisher": cfg.publisher,
        "enabled": cfg.enabled,
        "cadence": cfg.cadence,
        "raw_table": cfg.raw_table,
        "incremental_cursor": cfg.incremental_cursor,
        "row_limit": cfg.row_limit,
        "source_url": cfg.source_url,
        "page_views": cfg.page_views,
        "keywords": cfg.keywords,
        "description": cfg.description,
        "columns": [c.model_dump() for c in cfg.columns],
    }
    body = yaml.safe_dump(
        {"type": _DATASET_TYPE, "attributes": attributes},
        sort_keys=False,
        width=100,
        allow_unicode=True,
    )
    return "# Generated by data/scripts/scrape_healthdata_gov.py.\n" + body


def _write_dbt_sources(configs: list[DatasetConfig]) -> None:
    """Raw tables, one schema shared by every dataset (ADR-0013)."""
    enabled = [c for c in configs if c.enabled]
    doc = {
        "version": 2,
        "sources": [
            {
                "name": "healthdata_gov",
                "description": (
                    f"HealthData.gov (Socrata) raw tables, {_RAW_DATABASE}.{_RAW_SCHEMA}. "
                    "Generated by data/scripts/scrape_healthdata_gov.py."
                ),
                "database": _RAW_DATABASE,
                "schema": _RAW_SCHEMA,
                "tables": [
                    {
                        "name": c.raw_table,
                        "description": f"{c.name} ({c.publisher}). {c.source_url}",
                        "columns": [
                            {"name": col.name, "description": col.description}
                            for col in c.columns
                            if col.description
                        ],
                    }
                    for c in sorted(enabled, key=lambda c: c.raw_table)
                ],
            }
        ],
    }
    _DBT_SOURCES.parent.mkdir(parents=True, exist_ok=True)
    _DBT_SOURCES.write_text(
        "# Generated by data/scripts/scrape_healthdata_gov.py — do not edit by hand.\n"
        + yaml.safe_dump(doc, sort_keys=False, width=100)
    )


def _prune(out_dir: Path, keep: set[str]) -> int:
    """Drop generated dataset dirs no longer in the catalog (by dir name)."""
    removed = 0
    for child in out_dir.iterdir():
        if not child.is_dir() or child.name in keep:
            continue
        if (child / "defs.yaml").exists():
            shutil.rmtree(child)
            removed += 1
    return removed


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=_DEFAULT_OUT)
    ap.add_argument(
        "--limit", type=int, default=None, help="cap catalog entries scanned (default: all)"
    )
    ap.add_argument(
        "--top-n", type=int, default=8, help="enable this many datasets, by total page views"
    )
    ap.add_argument("--min-columns", type=int, default=2, help="skip datasets with fewer columns")
    ap.add_argument("--row-limit", type=int, default=500_000, help="row cap in every config")
    args = ap.parse_args()

    out_dir: Path = args.out
    out_dir.mkdir(parents=True, exist_ok=True)
    existing = _load_existing(out_dir)

    seen: dict[str, DatasetConfig] = {}
    scanned = 0
    for dataset in iter_catalog(limit=args.limit):
        scanned += 1
        if len(dataset.columns) < args.min_columns or dataset.id in seen:
            continue
        seen[dataset.id] = DatasetConfig.from_catalog(dataset, row_limit=args.row_limit)

    ranked = sorted(seen.values(), key=lambda c: c.page_views, reverse=True)
    top_ids = {c.id for c in ranked[: args.top_n]}

    slug_counts: dict[str, int] = {}
    table_counts: dict[str, int] = {}
    dirs: set[str] = set()
    for cfg in ranked:
        cfg.enabled = cfg.id in top_ids

        # Two distinct datasets can share a name (re-publishes). Disambiguate the
        # raw table and the directory with the 4x4 id so nothing collides.
        base_table = cfg.raw_table
        table_counts[base_table] = table_counts.get(base_table, 0) + 1
        if table_counts[base_table] > 1:
            cfg.raw_table = f"{base_table}_{cfg.id.replace('-', '_')}"

        if prior := existing.get(cfg.id):
            for key in _PRESERVE:
                if key in prior:
                    setattr(cfg, key, prior[key])

        slug = slugify(cfg.name)
        slug_counts[slug] = slug_counts.get(slug, 0) + 1
        dirname = slug if slug_counts[slug] == 1 else f"{slug}_{cfg.id}"
        dirs.add(dirname)
        (out_dir / dirname).mkdir(exist_ok=True)
        (out_dir / dirname / "defs.yaml").write_text(_dump_dataset(cfg))

    pruned = _prune(out_dir, dirs)
    _write_dbt_sources(list(seen.values()))

    by_cadence: dict[str, int] = {}
    for cfg in seen.values():
        if cfg.enabled:
            by_cadence[cfg.cadence] = by_cadence.get(cfg.cadence, 0) + 1

    print(f"scanned {scanned} catalog entries")
    print(f"wrote {len(dirs)} dataset components to {out_dir.relative_to(_REPO)} ({pruned} pruned)")
    print(f"enabled {len(top_ids)} by page views: {dict(sorted(by_cadence.items()))}")
    print(f"dbt sources -> {_DBT_SOURCES.relative_to(_REPO)}")


if __name__ == "__main__":
    main()
