#!/usr/bin/env python
"""One-time (re-runnable) scraper: CMS's data.json catalog -> per-dataset components.

    cd data && uv run python scripts/scrape_cms.py --top-n 5

Walks ``data.cms.gov/data.json`` and writes every dataset series with a live
API distribution as a Dagster **component instance** into

    ohdp_orchestration/defs/cms/datasets/defs.yaml

one YAML document per dataset, ``\n---\n`` between them — same multi-document
shape ``scrape_socrata.py`` writes, for the same reason (source positions stay
meaningful for "go to definition"; see that script's docstring). Also
regenerates the CMS dbt sources file.

The ``--top-n`` datasets by row count are written ``enabled: true`` (CMS's
catalog carries no popularity signal like Socrata's page views, so row count
is the nearest proxy for "this is a real, substantial dataset" — it is not a
relevance ranking, so the enabled set is expected to be hand-curated
afterward the same way ADR-0018 describes for CDC); the rest land disabled so
the catalog is captured without every dataset scheduling itself.

Re-running is safe: manual edits to ``enabled``, ``cadence`` and ``row_limit``
are preserved; everything else refreshes from the live catalog. The file is
rewritten whole, so datasets that left the catalog simply stop being emitted.

ADR-0026 (CMS isn't Socrata; this mirrors ``scrape_socrata.py``'s shape
without sharing its code, since the catalog and API underneath are unrelated).
"""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml

from ohdp_ingestion.cms import DatasetConfig, iter_catalog
from ohdp_ingestion.naming import database as ns_database
from ohdp_ingestion.naming import schema as ns_schema

_REPO = Path(__file__).resolve().parents[2]
_SCRIPT = "data/scripts/scrape_cms.py"
_DEFS_DIR = _REPO / "data/src/ohdp_orchestration/defs/cms"
_DATASETS_FILE = _DEFS_DIR / "datasets/defs.yaml"
_DBT_SOURCES = _REPO / "data/dbt/models/raw/_stg_cms__sources.yml"
_COMPONENT_TYPE = "ohdp_orchestration.defs.cms.component.CMSDataset"

# Attributes a human may override in a generated file; never stomped on re-run.
_PRESERVE = ("enabled", "cadence", "row_limit")


def _load_existing(defs_file: Path) -> dict[str, dict]:
    """id -> the `attributes` block of every dataset component already on disk."""
    existing: dict[str, dict] = {}
    if not defs_file.exists():
        return existing
    try:
        documents = list(yaml.safe_load_all(defs_file.read_text()))
    except yaml.YAMLError:
        return existing
    for data in documents:
        attrs = data.get("attributes") if isinstance(data, dict) else None
        if isinstance(attrs, dict) and attrs.get("id"):
            existing[attrs["id"]] = attrs
    return existing


def _dump_dataset(cfg: DatasetConfig) -> str:
    attributes = {
        "id": cfg.id,
        "name": cfg.name,
        "publisher": cfg.publisher,
        "enabled": cfg.enabled,
        "cadence": cfg.cadence,
        "raw_table": cfg.raw_table,
        "row_limit": cfg.row_limit,
        "source_url": cfg.source_url,
        "row_count": cfg.row_count,
        "keywords": cfg.keywords,
        "description": cfg.description,
        "columns": [c.model_dump() for c in cfg.columns],
    }
    return yaml.safe_dump(
        {"type": _COMPONENT_TYPE, "attributes": attributes},
        sort_keys=False,
        width=100,
        allow_unicode=True,
    )


def _write_dbt_sources(configs: list[DatasetConfig]) -> None:
    """Raw tables in the RAW.CMS namespace (ADR-0013)."""
    raw_database = ns_database("raw")
    raw_schema = ns_schema("raw", "cms")
    enabled = [c for c in configs if c.enabled]
    doc = {
        "version": 2,
        "sources": [
            {
                "name": "cms",
                "description": f"CMS (data.cms.gov) raw tables, {raw_database}.{raw_schema}. "
                f"Generated by {_SCRIPT}.",
                "database": raw_database,
                "schema": raw_schema,
                "tables": [
                    {
                        # `name` is the key models reference through `source()`
                        # and stays lower case; `identifier` is the physical
                        # table, which dlt creates upper case because Snowflake
                        # is the catalog (ADR-0019, ohdp_ingestion.sql_upper).
                        "name": c.raw_table,
                        "identifier": c.raw_table.upper(),
                        "description": f"{c.name} ({c.publisher}). {c.source_url}",
                        # Names always (they are what models select on);
                        # a `description` key only where CMS's data dictionary
                        # actually defines the column. Lower case for the same
                        # reason `name` is — Snowflake folds unquoted
                        # identifiers, and dlt wrote them upper case.
                        "columns": [
                            {"name": col.name.lower()}
                            | ({"description": col.description} if col.description else {})
                            for col in c.columns
                        ],
                    }
                    for c in sorted(enabled, key=lambda c: c.raw_table)
                ],
            }
        ],
    }
    _DBT_SOURCES.parent.mkdir(parents=True, exist_ok=True)
    _DBT_SOURCES.write_text(
        f"# Generated by {_SCRIPT} — do not edit by hand.\n"
        + yaml.safe_dump(doc, sort_keys=False, width=100)
    )


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", type=Path, default=None, help="override the datasets/defs.yaml path")
    ap.add_argument(
        "--limit", type=int, default=None, help="cap catalog entries scanned (default: all)"
    )
    ap.add_argument("--top-n", type=int, default=5, help="enable this many datasets, by row count")
    ap.add_argument("--row-limit", type=int, default=1_000_000, help="row cap in every config")
    ap.add_argument(
        "--no-details",
        action="store_true",
        help="skip the per-dataset data-viewer call (faster, but no row counts and no columns)",
    )
    ap.add_argument(
        "--no-column-docs",
        action="store_true",
        help="keep column names and types but skip the data dictionary lookup that describes them",
    )
    args = ap.parse_args()

    out_file: Path = args.out or _DATASETS_FILE
    out_file.parent.mkdir(parents=True, exist_ok=True)
    existing = _load_existing(out_file)

    seen: dict[str, DatasetConfig] = {}
    scanned = 0
    for dataset in iter_catalog(
        with_details=not args.no_details,
        with_column_docs=not args.no_column_docs,
        limit=args.limit,
    ):
        scanned += 1
        seen[dataset.id] = DatasetConfig.from_catalog(dataset, row_limit=args.row_limit)

    ranked = sorted(seen.values(), key=lambda c: c.row_count, reverse=True)
    top_ids = {c.id for c in ranked[: args.top_n]}

    documents: list[str] = []
    for cfg in ranked:
        cfg.enabled = cfg.id in top_ids

        if prior := existing.get(cfg.id):
            for key in _PRESERVE:
                if key in prior:
                    setattr(cfg, key, prior[key])

        documents.append(_dump_dataset(cfg))

    out_file.write_text(
        f"# Generated by {_SCRIPT} — do not edit by hand.\n"
        f"# One YAML document per dataset ({len(documents)}), newest catalog scrape.\n"
        + "\n---\n".join(documents)
    )
    _write_dbt_sources(list(seen.values()))

    by_cadence: dict[str, int] = {}
    for cfg in seen.values():
        if cfg.enabled:
            by_cadence[cfg.cadence] = by_cadence.get(cfg.cadence, 0) + 1

    enabled_total = sum(1 for c in seen.values() if c.enabled)
    print(f"data.cms.gov: scanned {scanned} catalog entries with a live API distribution")
    print(f"wrote {len(documents)} dataset components to {out_file.relative_to(_REPO)}")
    print(f"enabled {enabled_total}: {dict(sorted(by_cadence.items()))}")
    described = sum(1 for c in seen.values() if any(col.description for col in c.columns))
    columns_total = sum(len(c.columns) for c in seen.values())
    print(f"columns: {columns_total} scraped; {described} datasets have a data dictionary")
    print(f"dbt sources -> {_DBT_SOURCES.relative_to(_REPO)}")


if __name__ == "__main__":
    main()
