apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gqlproxy.fullname" . }}-authz
  labels:
    {{- include "gqlproxy.labels" . | nindent 4 }}
data:
  users.yaml: |
    users:
      {{- toYaml .Values.authz.users | nindent 6 }}
  groups.yaml: |
    {{- with .Values.authz.defaultGroups }}
    default_groups:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    groups:
      {{- toYaml .Values.authz.groups | nindent 6 }}
