"""CDC (data.cdc.gov) config-driven ingestion.

``component.py`` defines one component: ``CDCDataset`` — **one instance per
dataset**, under ``datasets/<slug>/defs.yaml`` (generated by
``data/scripts/scrape_socrata.py --domain data.cdc.gov``). Each emits a source
``AssetSpec`` under the ``sources/`` prefix and, when ``enabled``, a
``dlt``-backed table asset under ``ingestion/`` plus a ``snowflake/raw/`` label
that receives the load's materialization events.

The three cadence asset jobs + schedules need no per-instance config, so they
are plain code, not a component — see ``ohdp_orchestration.jobs.cdc`` /
``ohdp_orchestration.schedules.cdc``.
"""
