"""The data.cdc.gov binding of the shared Socrata dataset component.

One instance per dataset, under ``datasets/<slug>/defs.yaml`` (generated by
``data/scripts/scrape_socrata.py``). Everything this class does lives in
``ohdp_orchestration.components.socrata.SocrataDataset`` — see that module for
the asset shape. ADR-0018.

The three cadence asset jobs + schedules are plain code, not a component —
see ``ohdp_orchestration.jobs.cdc`` / ``ohdp_orchestration.schedules.cdc``.
"""

from __future__ import annotations

from typing import ClassVar

from ohdp_ingestion.cdc import CDC
from ohdp_ingestion.socrata import SocrataDomain
from ohdp_orchestration.components.socrata import SocrataDataset


class CDCDataset(SocrataDataset):
    """One data.cdc.gov dataset. Schema == ``DatasetConfig`` + ``group_name``."""

    SOCRATA: ClassVar[SocrataDomain] = CDC
