# The @asset body's `context` param is resolved by Dagster, not annotated
# here — `_validate_context_type_hint` compares the raw (string, under
# `annotations` import) annotation object-identically, so a typed annotation
# always fails.
# mypy: disable-error-code="no-untyped-def"
"""Turns every Cube measure into an OpenMetadata ``Metric`` entity
(ARCHITECTURE.md §7 `catalog/openmetadata/sync` — "Cube meta -> Metric
entities" — and the M2 build-order item, §8). Cube is the single definition
of every metric (ADR-0003); this sync is what makes that definition visible
to the discovery MCP the chatbot reads (§6), same job
``openmetadata_dagster_sync`` does for the Dagster asset catalog and
``openmetadata_sync`` does for Snowflake/dbt.

Bespoke, like ``openmetadata_dagster_sync``, not run through
``MetadataWorkflow``: ``openmetadata-ingestion==2.0.1`` ships no Cube source
connector, so there is no ``Source``/``Sink`` pipeline to configure. Instead
this reads Cube's own REST metadata endpoint
(``GET {CUBEJS_API_URL}/cubejs-api/v1/meta``, authenticated the same way any
Cube API caller is — a JWT signed with ``CUBEJS_API_SECRET``, ADR-0003 §consequences,
platform/helm/charts/cube/templates/NOTES.txt) and writes ``Metric`` entities
via OpenMetadata's SDK directly.

Cube's meta endpoint deliberately never exposes each measure's underlying SQL
(``sql``/``sql_table``) over the API, so ``metricExpression`` is left unset
rather than faked from the measure's name. The underlying Snowflake table is
instead resolved from the same compiled dbt manifest ``openmetadata_dbt_sync``
already reads (``_dbt_project.manifest_path``, baked into this image at build
time): for any cube generated by cube-dbt's ``{{ model.as_cube() }}``
(confirmed against ``cube_dbt.model.Model._as_cube`` — it sets the cube's
``name`` to the dbt model's own manifest ``name``, verbatim), the cube's name
is exactly that dbt model's name, so it can be looked up in the manifest
directly and joined to the ``Table`` entity ``openmetadata_snowflake_sync``
already ingested for it — no Cube API involvement, no guessing a name
mapping. A hand-written cube with no matching dbt model (or a model not
ingested into OM yet) just gets no table, the same graceful-skip
``openmetadata_dagster_sync`` uses when a downstream Snowflake table isn't
ingested yet.

That resolved table is used two ways, both needed: it's set as the Metric's
``assets`` (the flat "what this metric is computed from" reference OM shows
on the metric's own page), and a separate ``AddLineageRequest`` edge is drawn
from the ``Table`` to the ``Metric`` (the same ``metadata.add_lineage`` call
``openmetadata_dagster_sync`` uses for its own APIEndpoint -> Table edges).
``assets`` alone does *not* populate OM's lineage graph — it's a plain
entity-reference field, not a relationship the Lineage tab or
``get_entity_lineage`` traverses — so skipping the explicit edge leaves a
Metric with `assets` set but invisible in the UI's Lineage view and in any
lineage-graph traversal from the table's side.

One ``Metric`` per Cube measure, named ``<cube>__<measure>`` (Cube's own
fully-qualified ``<cube>.<measure>`` with the dot swapped for a double
underscore — ``Metric`` has no parent service, so its name doubles as its
FQN, and a literal dot there would collide with FQN part-separation). Every
dimension on a measure's own cube is attached to it as a ``MetricDimension``
— Cube has no notion of "this dimension only applies to that measure", so
all of a cube's dimensions apply to all of its measures. Every measure is
also cross-linked (``relatedMetrics``) to every *other* measure in the same
cube, for the same reason: Cube's meta endpoint has no finer-grained notion
of "these two measures are related" than "they're on the same cube," so
same-cube is the only grouping this sync can read off honestly. No
cross-cube relations are drawn.

The job/schedule for this asset live in ``ohdp_orchestration.jobs``/
``.schedules``, not here — this module is asset bodies only
(``ohdp_orchestration.assets``'s own convention, see its ``__init__.py``).
"""

from __future__ import annotations

import json
from typing import Any

import httpx
import jwt
from dagster import asset
from metadata.generated.schema.api.data.createMetric import CreateMetricRequest
from metadata.generated.schema.api.lineage.addLineage import AddLineageRequest
from metadata.generated.schema.entity.data.metric import (
    MetricDimension,
    MetricType,
)
from metadata.generated.schema.entity.data.metric import (
    Type as DimensionType,
)
from metadata.generated.schema.entity.data.table import Table
from metadata.generated.schema.entity.services.connections.metadata.openMetadataConnection import (
    OpenMetadataConnection,
)
from metadata.generated.schema.type.basic import (
    EntityName,
    FullyQualifiedEntityName,
    Markdown,
)
from metadata.generated.schema.type.entityLineage import EntitiesEdge
from metadata.generated.schema.type.entityReferenceList import EntityReferenceList
from metadata.ingestion.ometa.ometa_api import OpenMetadata
from metadata.ingestion.ometa.utils import build_entity_reference
from metadata.utils import fqn

from ohdp_orchestration.assets.openmetadata_sync import (
    _SNOWFLAKE_SERVICE_NAME,
    _openmetadata_server_config,
)
from ohdp_orchestration.assets.snowflake_dbt import _project as _dbt_project
from ohdp_shared import get_logger
from ohdp_shared.settings import settings

log = get_logger(__name__)

_GROUP_NAME = "openmetadata_sync"
_KEY_PREFIX = "openmetadata"

# Cube `aggType` (`semantic/cube/model/*.yml`'s measure `type:`) -> OM's
# MetricType. Cube's own "number"/"string"/... `type` field describes the
# measure's *result* type, not its aggregation, so this maps `aggType`
# specifically; anything not seen in this project's cubes yet falls back to
# OTHER rather than a hard failure.
_CUBE_AGG_TYPE_TO_METRIC_TYPE: dict[str, MetricType] = {
    "sum": MetricType.SUM,
    "avg": MetricType.AVERAGE,
    "count": MetricType.COUNT,
    "countDistinct": MetricType.COUNT,
    "countDistinctApprox": MetricType.COUNT,
    "min": MetricType.MIN,
    "max": MetricType.MAX,
    "number": MetricType.DERIVED,
}


def _cube_auth_token() -> str:
    """A Cube API JWT — Cube's own auth scheme (no claims needed for the
    default `queryRewrite`, which only reads `securityContext.tier`;
    unset here means every catalog sync runs as an untiered caller)."""
    return jwt.encode({}, settings.cube_api_secret, algorithm="HS256")


def _fetch_cube_meta() -> list[dict[str, Any]]:
    """One round-trip to Cube's metadata endpoint for every cube's measures
    and dimensions — the same endpoint the Cube Playground and MCP surface
    use, not a bespoke query."""
    response = httpx.get(
        f"{settings.cube_api_url}/cubejs-api/v1/meta",
        headers={"Authorization": _cube_auth_token()},
        timeout=30,
    )
    if response.is_error:
        # `raise_for_status()` alone drops the response body — Cube puts the
        # actual schema-compile/auth error there, and the Dagster run's own
        # log is often the only place that's easier to reach than the Cube
        # pod's own logs.
        raise RuntimeError(f"Cube meta request failed ({response.status_code}): {response.text}")
    payload: dict[str, Any] = response.json()
    cubes: list[dict[str, Any]] = payload["cubes"]
    return cubes


def _dbt_model_table_index() -> dict[str, tuple[str, str, str]]:
    """Maps each dbt model's own manifest ``name`` (what a cube-dbt
    ``{{ model.as_cube() }}``-templated cube's ``name`` is set to verbatim —
    confirmed against ``cube_dbt.model.Model._as_cube``) to the physical
    Snowflake table it builds: ``(database, schema, table)``, upper-cased to
    match Snowflake's own unquoted-identifier casing — what
    ``openmetadata_snowflake_sync`` actually ingested Table entities under —
    not the lower-case values the manifest itself stores. Read from the same
    manifest.json baked into this image that ``openmetadata_dbt_sync``
    already reads (``_dbt_project.manifest_path``); only ``model`` nodes are
    indexed (seeds/tests/etc. never become cubes)."""
    manifest = json.loads(_dbt_project.manifest_path.read_text())
    index: dict[str, tuple[str, str, str]] = {}
    for node in manifest["nodes"].values():
        if node.get("resource_type") != "model":
            continue
        table = str(node.get("alias") or node["name"])
        index[node["name"]] = (
            str(node["database"]).upper(),
            str(node["schema"]).upper(),
            table.upper(),
        )
    return index


def _resolve_table(
    cube_name: str,
    dbt_table_index: dict[str, tuple[str, str, str]],
    metadata: OpenMetadata[Any, Any],
) -> Table | None:
    """The Snowflake Table a cube's measures are computed over. Only
    resolvable for dbt-templated cubes (see this module's docstring) and only
    once that table has actually been ingested by
    ``openmetadata_snowflake_sync`` — a hand-written cube with no matching
    dbt model, or one not ingested yet, gets no table, not an error (same
    graceful-skip ``openmetadata_dagster_sync`` uses for its own
    not-yet-ingested downstream tables). Callers use the result both as the
    Metric's ``assets`` reference and as the source of an explicit
    ``add_lineage`` edge — see this module's docstring for why both are
    needed."""
    coordinates = dbt_table_index.get(cube_name)
    if not coordinates:
        return None
    database, schema, table = coordinates
    table_fqn = fqn.build(
        metadata=metadata,
        entity_type=Table,
        service_name=_SNOWFLAKE_SERVICE_NAME,
        database_name=database,
        schema_name=schema,
        table_name=table,
    )
    if not table_fqn:
        return None
    return metadata.get_by_name(entity=Table, fqn=table_fqn)


def _metric_dimension(dimension: dict[str, Any]) -> MetricDimension:
    short_name = str(dimension["name"]).split(".")[-1]
    return MetricDimension(
        name=short_name,
        type=DimensionType.TIME if dimension.get("type") == "time" else DimensionType.CATEGORICAL,
        description=dimension.get("description"),
    )


def _metric_entity_name(measure: dict[str, Any]) -> str:
    """`<cube>__<measure>` for one Cube measure — see this module's docstring
    for why the OM entity name swaps Cube's own `<cube>.<measure>` dot for a
    double underscore. Since `Metric` has no parent service, this doubles as
    the entity's FQN, which is what makes it usable directly in
    `relatedMetrics` without a separate `fqn.build` round-trip."""
    cube_name, _, short_name = str(measure["name"]).partition(".")
    return f"{cube_name}__{short_name}"


def _metric_request(
    measure: dict[str, Any],
    dimensions: list[MetricDimension],
    assets: EntityReferenceList | None,
    related_metrics: list[FullyQualifiedEntityName] | None,
) -> CreateMetricRequest:
    """Builds the CreateMetricRequest for one Cube measure. `assets` is the
    cube's underlying Snowflake Table, if one was resolved (`_resolve_table`)
    — every measure in the same cube shares it. `related_metrics` is every
    *other* measure in the same cube (Cube has no cross-cube measure
    relationships to read, so this sync never links across cubes)."""
    return CreateMetricRequest(
        name=EntityName(_metric_entity_name(measure)),
        displayName=measure.get("title"),
        description=Markdown(measure["description"]) if measure.get("description") else None,
        metricType=_CUBE_AGG_TYPE_TO_METRIC_TYPE.get(str(measure.get("aggType")), MetricType.OTHER),
        dimensions=dimensions or None,
        assets=assets,
        relatedMetrics=related_metrics or None,
    )


def _om_client() -> OpenMetadata[Any, Any]:
    return OpenMetadata(OpenMetadataConnection.model_validate(_openmetadata_server_config()))


@asset(key_prefix=_KEY_PREFIX, group_name=_GROUP_NAME, kinds={"openmetadata"})
def openmetadata_cube_metrics_sync(context) -> None:
    """Reads every cube's measures/dimensions from Cube's metadata endpoint
    and upserts one OpenMetadata ``Metric`` entity per measure, linked
    (``assets`` plus an explicit lineage edge — see this module's docstring
    for why both) to its underlying Snowflake Table where one can be
    resolved. See this module's docstring for why this talks to Cube's REST
    API and OM's SDK directly rather than going through ``MetadataWorkflow``,
    and how lineage is joined through the dbt manifest rather than Cube's
    API."""
    context.log.info(f"Reading Cube metadata from {settings.cube_api_url}")
    cubes = _fetch_cube_meta()
    dbt_table_index = _dbt_model_table_index()

    metadata = _om_client()
    synced = 0
    linked = 0
    for cube in cubes:
        dimensions = [_metric_dimension(d) for d in cube.get("dimensions", [])]
        table_entity = _resolve_table(cube["name"], dbt_table_index, metadata)
        assets = (
            EntityReferenceList([build_entity_reference(table_entity)]) if table_entity else None
        )
        linked += bool(table_entity)
        measures = cube.get("measures", [])
        measure_names = [_metric_entity_name(m) for m in measures]
        for measure in measures:
            entity_name = _metric_entity_name(measure)
            related_metrics = [
                FullyQualifiedEntityName(name) for name in measure_names if name != entity_name
            ]
            metric_entity = metadata.create_or_update(
                _metric_request(measure, dimensions, assets, related_metrics)
            )
            synced += 1
            if table_entity:
                metadata.add_lineage(
                    AddLineageRequest(
                        edge=EntitiesEdge(
                            fromEntity=build_entity_reference(table_entity),
                            toEntity=build_entity_reference(metric_entity),
                        )
                    )
                )

    context.log.info(
        f"Synced {synced} Cube measures into OpenMetadata Metric entities "
        f"({linked} cubes linked to their Snowflake table)"
    )
