# The @asset body's `context` param is resolved by Dagster, not annotated
# here — see openmetadata_seed_sync.py's identical header comment for why.
# mypy: disable-error-code="no-untyped-def"
"""Fills the public Literature page's trending feed
(``apps/web/src/pages/Literature.tsx``'s 🔥 badge,
``apps/api/src/hub_api/content.py``'s ``curated_literature.trending``) —
replaces the health-topic half of the earlier domain-wide ``literature_sync``
asset, which wrote to OpenMetadata's Context Center instead of anywhere a
public page could read (see ``ohdp_orchestration.assets
.literature_dataset_sync`` for the other half of that split, which does still
write to OM). That table has had no writer since it was added; this is what
"fill our news feed" turned into an actual write path.

Ranks each seeded Domain's OpenAlex subfields by recent citation count
(``ohdp_ingestion.literature.select_trending_literature``, driven by
``seed/literature_domains.yml``), cross-checks against Europe PMC's MeSH
headings the same way the asset it replaced did, and POSTs the combined result
to hub-api's internal ingest route as one batch —
see ``hub_api.content.replace_trending_literature`` for the upsert/retire
semantics (a paper that falls out of this run's selection loses its trending
flag rather than being deleted).

**Why HTTP to hub-api rather than a direct Postgres connection:** hub-api is
the sole writer to the `app` database everywhere else in this codebase (see
``hub_api.content``'s module docstring); this asset stays consistent with that
instead of becoming a second one. The call is authenticated with a shared
bearer token (``OHDP_INTERNAL_INGEST_TOKEN``), generated by platform-base and
injected into both sides — same pattern as the hub-api/Cube shared secret
(``platform/helm/charts/platform-base/templates/secrets.yaml``,
``ohdp_shared.settings.internal_ingest_token``'s own docstring).

**Summaries are the paper's own OpenAlex abstract, truncated** — not an
AI-authored blurb, despite the Literature page's copy ("Summaries are ours;
the science is theirs"). Writing an actual summary would mean adding an LLM
call to this asset (a model backend, a prompt, cost accounting this ingestion
job doesn't otherwise have), which is out of scope here; ``_summary`` is a
clearly-labelled placeholder for that, not a finished feature.
"""

from __future__ import annotations

from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import httpx
from dagster import asset

from ohdp_ingestion.literature import OpenAlexClient, SelectedWork, select_trending_literature
from ohdp_ingestion.literature.selection import load_domain_selections
from ohdp_shared import get_logger
from ohdp_shared.settings import settings

log = get_logger(__name__)

_GROUP_NAME = "openmetadata_sync"
_KEY_PREFIX = "openmetadata"

_SEED_PATH = Path(__file__).resolve().parents[1] / "seed" / "literature_domains.yml"

_TRENDING_INGEST_PATH = "/api/internal/literature/trending"
_SUMMARY_MAX_CHARS = 320


def _summary(abstract: str) -> str:
    """A placeholder summary — the paper's own abstract, trimmed to a
    card-sized blurb. See the module docstring's own caveat: this is not the
    AI-authored summary the Literature page's copy implies."""
    text = abstract.strip()
    if len(text) <= _SUMMARY_MAX_CHARS:
        return text
    return text[:_SUMMARY_MAX_CHARS].rsplit(" ", 1)[0] + "…"


def _trending_item(entry: SelectedWork) -> dict[str, Any]:
    work = entry.work
    return {
        "title": work.title or work.openalex_id,
        "authors": work.authors,
        "venue": work.venue,
        "year": work.publication_year,
        "url": work.url,
        "doi": work.doi,
        "summary": _summary(work.abstract),
        "tags": sorted(entry.domains),
    }


@asset(key_prefix=_KEY_PREFIX, group_name=_GROUP_NAME, kinds={"openmetadata"})
def literature_trending_sync(context) -> None:
    """Ranks trending literature per seeded Domain and replaces hub-api's
    trending feed with the combined result in one batch call."""
    selections = load_domain_selections(_SEED_PATH)
    with OpenAlexClient(contact_email=settings.openalex_contact_email) as openalex:
        selected = select_trending_literature(
            selections,
            openalex=openalex,
            current_year=datetime.now(UTC).year,
            contact_email=settings.openalex_contact_email,
        )

    items = [_trending_item(entry) for entry in selected.values()]
    response = httpx.post(
        f"{settings.hub_api_url.rstrip('/')}{_TRENDING_INGEST_PATH}",
        json=items,
        headers={"Authorization": f"Bearer {settings.internal_ingest_token}"},
        timeout=30.0,
    )
    response.raise_for_status()

    context.log.info(
        f"Synced {len(items)} trending literature items across {len(selections)} domains"
    )
