"""CMS (data.cms.gov) config-driven ingestion.

``component.py`` defines one component: ``CMSDataset`` — **one instance per
dataset**, one ``---`` document in ``datasets/defs.yaml`` (generated by
``data/scripts/scrape_cms.py``). Each emits a source ``AssetSpec`` under the
``sources/`` prefix and, when ``enabled``, a ``dlt``-backed table asset under
``ingestion/`` plus a ``lakehouse/raw/`` label that receives the load's
materialization events — the same shape ADR-0008/0018 established for
Socrata sources, over CMS's own REST API instead (ADR-0026).

The three cadence asset jobs + schedules need no per-instance config, so they
are plain code, not a component — see ``ohdp_orchestration.jobs.cms`` /
``ohdp_orchestration.schedules.cms``.
"""
