# The @dlt_assets body is built per instance; its `context` param is resolved
# by Dagster, not annotated here.
# mypy: disable-error-code="no-untyped-def, no-untyped-call, type-arg, arg-type"
"""``CMSDataset`` — one component **instance per CMS dataset**, the CMS
binding of the same three-asset shape
``ohdp_orchestration.components.socrata.SocrataDataset`` gives every Socrata
domain (ADR-0008, ADR-0018). CMS isn't Socrata (ADR-0026), so this isn't a
subclass of it — but it produces the identical asset graph, for the same
reason: lineage and the cadence jobs need the same three nodes regardless of
what's underneath.

There's exactly one CMS domain, unlike Socrata's HealthData.gov/CDC/etc., so
there is no base-class-plus-three-line-subclass split here the way
``ohdp_orchestration.defs.cdc.component.CDCDataset`` binds
``ohdp_orchestration.components.socrata.SocrataDataset`` — this class *is*
the whole thing, one instance per ``---`` document in ``datasets/defs.yaml``
(generated by ``data/scripts/scrape_cms.py``).

Each instance emits up to three assets:

* a **source asset** ``sources/cms/<raw_table>`` — an unexecutable
  ``AssetSpec`` (kind ``cms``) standing for the dataset as CMS publishes it.
  Always; never materialized.
* a **table asset** ``ingestion/cms/<raw_table>`` — a ``@dlt_assets``
  pipeline, ``deps=[source asset]``, kind ``dlt`` + whatever the destination
  actually is that run. Only when ``enabled: true``.
* a **raw-layer asset** ``lakehouse/raw/cms/<raw_table>`` — an unexecutable
  ``AssetSpec`` labelling the Iceberg table in the catalog, which receives a
  *runless* materialization event from the table asset's op. Only when
  ``enabled: true``.

Disabled datasets have only the source node, so the whole catalog stays
visible to the OpenMetadata Dagster ingestion; enabling one adds the two
downstream nodes without touching it.

The cadence asset jobs + schedules need no per-instance config, so they are
plain code rather than a component — see ``ohdp_orchestration.jobs.cms``.
"""

from __future__ import annotations

from dataclasses import dataclass

from dagster import (
    AssetKey,
    AssetMaterialization,
    AssetsDefinition,
    AssetSpec,
    Definitions,
    MetadataValue,
)
from dagster.components import Component, ComponentLoadContext, Resolvable
from dagster_dlt import DagsterDltResource, DagsterDltTranslator, dlt_assets
from dagster_dlt.translator import DltResourceTranslatorData

from ohdp_ingestion import naming
from ohdp_ingestion.cms import DatasetConfig, build_pipeline, cms_source
from ohdp_orchestration.resources.dlt import DLT_RESOURCE
from ohdp_shared import get_logger

log = get_logger(__name__)

SOURCE = "cms"

# Same prefixes as ohdp_orchestration.components.socrata — kept identical so
# the two sources' assets read the same way in the Dagster UI and select the
# same way for OpenMetadata's Dagster ingestion.
SOURCES_PREFIX = "sources"
INGESTION_PREFIX = "ingestion"
LAKEHOUSE_PREFIX = "lakehouse"


@dataclass
class _TableTranslator(DagsterDltTranslator):
    """Grafts ``CMSDataset._table_spec()`` onto the spec ``DagsterDltTranslator``
    derives from the dlt resource — see
    ``ohdp_orchestration.components.socrata._TableTranslator``, which this
    mirrors exactly."""

    spec: AssetSpec

    def get_asset_spec(self, data: DltResourceTranslatorData) -> AssetSpec:
        return (
            super()
            .get_asset_spec(data)
            .replace_attributes(
                key=self.spec.key,
                deps=self.spec.deps,
                description=self.spec.description,
                group_name=self.spec.group_name,
            )
            .merge_attributes(
                tags=self.spec.tags,
                metadata=self.spec.metadata,
            )
        )


class CMSDataset(Component, DatasetConfig, Resolvable):
    """One CMS dataset. Schema == ``DatasetConfig`` + ``group_name``."""

    group_name: str | None = None

    @property
    def _group(self) -> str:
        return self.group_name or SOURCE

    @property
    def _raw_namespace(self) -> str:
        """``"RAW.CMS"`` (ADR-0013)."""
        return naming.namespace("raw", SOURCE)

    # --- keys ---------------------------------------------------------------
    @property
    def catalog_key(self) -> AssetKey:
        return AssetKey([SOURCES_PREFIX, SOURCE, self.raw_table])

    @property
    def table_key(self) -> AssetKey:
        return AssetKey([INGESTION_PREFIX, SOURCE, self.raw_table])

    def _lakehouse_raw_key(self, table: str) -> AssetKey:
        """Label for where a table lives in the raw layer — matches dbt's
        compiled source-node asset key (ADR-0019); see
        ``ohdp_orchestration.components.socrata`` for the identical logic on
        the Socrata side."""
        return AssetKey(
            [
                LAKEHOUSE_PREFIX,
                naming.database("raw").lower(),
                naming.schema("raw", SOURCE).lower(),
                table.lower(),
            ]
        )

    @property
    def lakehouse_raw_key(self) -> AssetKey:
        return self._lakehouse_raw_key(self.raw_table)

    # --- specs -------------------------------------------------------------
    def _catalog_spec(self) -> AssetSpec:
        metadata: dict[str, object] = {
            "cms_dataset_id": self.id,
            "publisher": self.publisher,
            "cadence": self.cadence,
            "enabled": self.enabled,
            "lands_in": (
                f"{self._raw_namespace}.{self.raw_table}" if self.enabled else "(not ingested)"
            ),
            "write_disposition": "replace (CMS republishes the whole dataset each vintage)",
            "row_count_at_scrape": MetadataValue.int(self.row_count),
            "keywords": MetadataValue.json(self.keywords),
        }
        if self.source_url:
            metadata["dagster/uri"] = MetadataValue.url(self.source_url)

        return AssetSpec(
            key=self.catalog_key,
            group_name=f"{SOURCES_PREFIX}_{self._group}",
            description=self.description or self.name,
            metadata=metadata,
            tags={"domain": SOURCE, "enabled": str(self.enabled).lower()},
            kinds={"cms"},
        )

    def _table_spec(self) -> AssetSpec:
        metadata: dict[str, object] = {
            "dagster/table_name": f"{self._raw_namespace}.{self.raw_table}",
            "cms_dataset_id": self.id,
            "write_disposition": "replace",
        }
        return AssetSpec(
            key=self.table_key,
            deps=[self.catalog_key],
            group_name=f"{INGESTION_PREFIX}_{self._group}",
            description=f"{self.name} — replaces {self._raw_namespace}.{self.raw_table} by dlt.",
            metadata=metadata,
            # cadence lives only on the table asset: it is what the cadence
            # schedules select on.
            tags={"domain": SOURCE, "cadence": self.cadence},
        )

    def _lakehouse_raw_spec(self) -> AssetSpec:
        return AssetSpec(
            key=self.lakehouse_raw_key,
            deps=[self.table_key],
            group_name=f"{LAKEHOUSE_PREFIX}_raw",
            description=f"{self.name} — as dbt's `{SOURCE}` source sees it.",
            tags={"domain": LAKEHOUSE_PREFIX, "layer": "raw"},
            kinds={"iceberg"},
        )

    # --- defs ---------------------------------------------------------------
    def _table_asset(self) -> AssetsDefinition:
        cfg = self
        translator = _TableTranslator(spec=self._table_spec())

        @dlt_assets(
            dlt_source=cms_source(cfg.id, cfg.raw_table, row_limit=cfg.row_limit),
            dlt_pipeline=build_pipeline(pipeline_name=f"{SOURCE}_{cfg.raw_table}", source=SOURCE),
            name=cfg.raw_table,
            dagster_dlt_translator=translator,
            op_tags={"cadence": cfg.cadence},
        )
        def _assets(context, dlt: DagsterDltResource):
            # Mirrors ohdp_orchestration.components.socrata's table asset op —
            # see that module's docstring for why table_names has to come off
            # the run event rather than the pipeline object afterward.
            for event in dlt.run(context=context, loader_file_format="parquet"):
                yield event
                raw_table_names = (event.metadata or {}).get("table_names")
                table_names = (
                    raw_table_names if isinstance(raw_table_names, list) else [cfg.raw_table]
                )
                for table_name in table_names:
                    context.instance.report_runless_asset_event(
                        AssetMaterialization(
                            asset_key=cfg._lakehouse_raw_key(table_name),
                            description="Represents data copied into the raw layer.",
                        )
                    )

        return _assets

    def build_defs(self, context: ComponentLoadContext) -> Definitions:
        assets: list = [self._catalog_spec()]
        resources: dict = {}
        if self.enabled:
            assets.append(self._table_asset())
            assets.append(self._lakehouse_raw_spec())
            resources["dlt"] = DLT_RESOURCE
        return Definitions(assets=assets, resources=resources)
