# The @dlt_assets body is built per instance; its `context` param is resolved
# by Dagster, not annotated here.
# mypy: disable-error-code="no-untyped-def, no-untyped-call, type-arg, arg-type"
"""``OpenAQDataset`` — the OpenAQ binding of the same three-asset shape
``ohdp_orchestration.components.socrata.SocrataDataset``/
``ohdp_orchestration.defs.cms.component.CMSDataset`` give every other raw
source (ADR-0008, ADR-0018, ADR-0026). OpenAQ isn't Socrata or CMS, but it
produces the identical asset graph, for the same reason: lineage and the
cadence jobs need the same three nodes regardless of what's underneath.

Unlike Socrata/CMS, OpenAQ's REST API isn't a catalog of many independent
datasets — ``/v3/locations`` is one global, constantly-updated snapshot of
every registered monitoring station. So there is exactly one instance today
(``locations``), and ``datasets/defs.yaml`` is hand-maintained rather than
generated by a scraper.

Each instance emits up to three assets:

* a **source asset** ``sources/openaq/<raw_table>`` — an unexecutable
  ``AssetSpec`` (kind ``openaq``) standing for the resource as OpenAQ
  publishes it. Always; never materialized.
* a **table asset** ``ingestion/openaq/<raw_table>`` — a ``@dlt_assets``
  pipeline, ``deps=[source asset]``, kind ``dlt`` + whatever the destination
  actually is that run. Only when ``enabled: true``.
* a **raw-layer asset** ``lakehouse/raw/openaq/<raw_table>`` — an unexecutable
  ``AssetSpec`` labelling the Iceberg table in the catalog, which receives a
  *runless* materialization event from the table asset's op. Only when
  ``enabled: true``.

The cadence asset jobs + schedules need no per-instance config, so they are
plain code rather than a component — see ``ohdp_orchestration.jobs.openaq``.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from dagster import (
    AssetKey,
    AssetMaterialization,
    AssetsDefinition,
    AssetSpec,
    Definitions,
    MetadataValue,
)
from dagster.components import Component, ComponentLoadContext, Resolvable
from dagster_dlt import DagsterDltResource, DagsterDltTranslator, dlt_assets
from dagster_dlt.translator import DltResourceTranslatorData

from ohdp_ingestion import naming
from ohdp_ingestion.openaq import (
    DatasetConfig,
    build_pipeline,
    openaq_locations_source,
    openaq_monthly_measurements_source,
)
from ohdp_orchestration.resources.dlt import DLT_RESOURCE
from ohdp_shared import get_logger

log = get_logger(__name__)

SOURCE = "openaq"

# Same prefixes as ohdp_orchestration.components.socrata / defs.cms.component
# — kept identical so every source's assets read the same way in the Dagster
# UI and select the same way for OpenMetadata's Dagster ingestion.
SOURCES_PREFIX = "sources"
INGESTION_PREFIX = "ingestion"
LAKEHOUSE_PREFIX = "lakehouse"


@dataclass
class _TableTranslator(DagsterDltTranslator):
    """Grafts ``OpenAQDataset._table_spec()`` onto the spec
    ``DagsterDltTranslator`` derives from the dlt resource — see
    ``ohdp_orchestration.components.socrata._TableTranslator``, which this
    mirrors exactly."""

    spec: AssetSpec

    def get_asset_spec(self, data: DltResourceTranslatorData) -> AssetSpec:
        return (
            super()
            .get_asset_spec(data)
            .replace_attributes(
                key=self.spec.key,
                deps=self.spec.deps,
                description=self.spec.description,
                group_name=self.spec.group_name,
            )
            .merge_attributes(
                tags=self.spec.tags,
                metadata=self.spec.metadata,
            )
        )


class OpenAQDataset(Component, DatasetConfig, Resolvable):
    """One OpenAQ REST resource (today: just ``locations``). Schema ==
    ``DatasetConfig`` + ``group_name``."""

    group_name: str | None = None

    @property
    def _group(self) -> str:
        return self.group_name or SOURCE

    @property
    def _raw_namespace(self) -> str:
        """``"RAW.OPENAQ"`` (ADR-0013)."""
        return naming.namespace("raw", SOURCE)

    # --- keys ---------------------------------------------------------------
    @property
    def catalog_key(self) -> AssetKey:
        return AssetKey([SOURCES_PREFIX, SOURCE, self.raw_table])

    @property
    def table_key(self) -> AssetKey:
        return AssetKey([INGESTION_PREFIX, SOURCE, self.raw_table])

    def _lakehouse_raw_key(self, table: str) -> AssetKey:
        """Label for where a table lives in the raw layer — matches dbt's
        compiled source-node asset key (ADR-0019); see
        ``ohdp_orchestration.components.socrata`` for the identical logic on
        the Socrata side."""
        return AssetKey(
            [
                LAKEHOUSE_PREFIX,
                naming.database("raw").lower(),
                naming.schema("raw", SOURCE).lower(),
                table.lower(),
            ]
        )

    @property
    def lakehouse_raw_key(self) -> AssetKey:
        return self._lakehouse_raw_key(self.raw_table)

    @property
    def _write_disposition(self) -> str:
        """Mirrors the disposition ``ohdp_ingestion.openaq.source`` actually
        picks: ``locations`` has no per-row cursor at all, so always
        ``replace``; ``monthly_measurements`` is ``append`` with a bounded
        lookback once ``lookback_months`` is set, else a full-history
        ``replace`` (see that module's docstring)."""
        if self.resource == "monthly_measurements" and self.lookback_months is not None:
            months = self.lookback_months
            return f"append (trailing {months} months -- see ohdp_ingestion.openaq.source)"
        return "replace (no per-row cursor -- see ohdp_ingestion.openaq.source)"

    # --- specs ---------------------------------------------------------------
    def _catalog_spec(self) -> AssetSpec:
        metadata: dict[str, object] = {
            "publisher": self.publisher,
            "cadence": self.cadence,
            "enabled": self.enabled,
            "resource": self.resource,
            "lands_in": (
                f"{self._raw_namespace}.{self.raw_table}" if self.enabled else "(not ingested)"
            ),
            "write_disposition": self._write_disposition,
        }
        if self.resource == "monthly_measurements":
            metadata["countries"] = MetadataValue.json(self.countries)
            metadata["parameters"] = MetadataValue.json(self.parameters)
            metadata["reference_monitors_only"] = self.reference_monitors_only
            metadata["lookback_months"] = self.lookback_months
        if self.source_url:
            metadata["dagster/uri"] = MetadataValue.url(self.source_url)

        return AssetSpec(
            key=self.catalog_key,
            group_name=f"{SOURCES_PREFIX}_{self._group}",
            description=self.description or self.name,
            metadata=metadata,
            tags={"domain": SOURCE, "enabled": str(self.enabled).lower()},
            kinds={"openaq"},
        )

    def _table_spec(self) -> AssetSpec:
        disposition = self._write_disposition
        metadata: dict[str, object] = {
            "dagster/table_name": f"{self._raw_namespace}.{self.raw_table}",
            "write_disposition": disposition,
        }
        verb = "appends to" if disposition.startswith("append") else "replaces"
        return AssetSpec(
            key=self.table_key,
            deps=[self.catalog_key],
            group_name=f"{INGESTION_PREFIX}_{self._group}",
            description=f"{self.name} — {verb} {self._raw_namespace}.{self.raw_table} by dlt.",
            metadata=metadata,
            # cadence lives only on the table asset: it is what the cadence
            # schedules select on.
            tags={"domain": SOURCE, "cadence": self.cadence},
        )

    def _lakehouse_raw_spec(self) -> AssetSpec:
        return AssetSpec(
            key=self.lakehouse_raw_key,
            deps=[self.table_key],
            group_name=f"{LAKEHOUSE_PREFIX}_raw",
            description=f"{self.name} — as dbt's `{SOURCE}` source sees it.",
            tags={"domain": LAKEHOUSE_PREFIX, "layer": "raw"},
            kinds={"iceberg"},
        )

    # --- defs ---------------------------------------------------------------
    def _dlt_source(self) -> Any:
        """Dispatches on ``resource`` — see ``DatasetConfig``'s docstring for
        why both resources share this one component/config shape instead of
        each getting its own."""
        if self.resource == "locations":
            return openaq_locations_source(self.raw_table, row_limit=self.row_limit)
        return openaq_monthly_measurements_source(
            self.raw_table,
            countries=self.countries,
            parameters=self.parameters,
            reference_monitors_only=self.reference_monitors_only,
            row_limit=self.row_limit,
            lookback_months=self.lookback_months,
        )

    def _table_asset(self) -> AssetsDefinition:
        cfg = self
        translator = _TableTranslator(spec=self._table_spec())

        @dlt_assets(
            dlt_source=cfg._dlt_source(),
            dlt_pipeline=build_pipeline(pipeline_name=f"{SOURCE}_{cfg.raw_table}", source=SOURCE),
            name=cfg.raw_table,
            dagster_dlt_translator=translator,
            op_tags={"cadence": cfg.cadence},
        )
        def _assets(context, dlt: DagsterDltResource):
            # Mirrors defs.cms.component's table asset op — see that
            # module's docstring (via components.socrata) for why
            # table_names has to come off the run event rather than the
            # pipeline object afterward.
            for event in dlt.run(context=context, loader_file_format="parquet"):
                yield event
                raw_table_names = (event.metadata or {}).get("table_names")
                table_names = (
                    raw_table_names if isinstance(raw_table_names, list) else [cfg.raw_table]
                )
                for table_name in table_names:
                    context.instance.report_runless_asset_event(
                        AssetMaterialization(
                            asset_key=cfg._lakehouse_raw_key(table_name),
                            description="Represents data copied into the raw layer.",
                        )
                    )

        return _assets

    def build_defs(self, context: ComponentLoadContext) -> Definitions:
        assets: list = [self._catalog_spec()]
        resources: dict = {}
        if self.enabled:
            assets.append(self._table_asset())
            assets.append(self._lakehouse_raw_spec())
            resources["dlt"] = DLT_RESOURCE
        return Definitions(assets=assets, resources=resources)
