#!/usr/bin/env bash
# Create the Apache Polaris `ohdp` catalog (ADR-0010).
#
# The schema + `ohdp` realm/root-principal are bootstrapped by the
# `bootstrap-schema` init container on the Polaris pod (values/polaris.yaml).
# This step is the other half — the INTERNAL catalog `ohdp` (warehouse root
# s3://<bucket>, allowed locations under it) — which needs the server running,
# so it cannot be an init container. `make -C platform/helm polaris` runs it
# right after `helm upgrade --install ... --wait`.
#
# Idempotent: an existing catalog (HTTP 409) is fine.
#
# Root principal credentials == the pipeline's OHDP_ICEBERG_CREDENTIAL
# ("<clientId>:<clientSecret>", ADR-0010), generated by platform-base. The script
# reads it from the `polaris-principal` secret in `data`; override with the env
# var for a one-off.
set -euo pipefail

: "${KUBECONFIG:?export KUBECONFIG first}"

NS=data
CATALOG=ohdp
BUCKET="${OHDP_SPACES_BUCKET:-ohdp-warehouse}"
S3_ENDPOINT="${OHDP_SPACES_ENDPOINT_URL:-https://nyc3.digitaloceanspaces.com}"
S3_REGION="${OHDP_SPACES_REGION:-nyc3}"

cred="${OHDP_ICEBERG_CREDENTIAL:-}"
if [[ -z "$cred" ]]; then
  cred=$(kubectl -n "$NS" get secret polaris-principal \
    -o jsonpath='{.data.OHDP_ICEBERG_CREDENTIAL}' 2>/dev/null | base64 -d || true)
fi
[[ -n "$cred" && "$cred" == *:* ]] || {
  echo "OHDP_ICEBERG_CREDENTIAL (<clientId>:<clientSecret>) not set and not found in the polaris-principal secret" >&2
  exit 1
}
CLIENT_ID="${cred%%:*}"
CLIENT_SECRET="${cred#*:}"

echo "==> creating catalog '$CATALOG' via the management API"
base="http://polaris.$NS.svc.cluster.local:8181"
# Run curl+jq from a throwaway pod in-cluster so we hit the ClusterIP service.
kubectl -n "$NS" run polaris-catalog-init --rm -i --restart=Never \
  --image=badouralix/curl-jq --quiet -- sh -euc "
    token=\$(curl -sf -X POST '$base/api/catalog/v1/oauth/tokens' \
      -d grant_type=client_credentials \
      -d client_id='$CLIENT_ID' -d client_secret='$CLIENT_SECRET' \
      -d scope='PRINCIPAL_ROLE:ALL' | jq -r .access_token)
    [ -n \"\$token\" ] && [ \"\$token\" != null ] || { echo 'token request failed' >&2; exit 1; }

    code=\$(curl -s -o /tmp/o -w '%{http_code}' -X POST '$base/api/management/v1/catalogs' \
      -H \"Authorization: Bearer \$token\" -H 'Content-Type: application/json' \
      -d '{
        \"catalog\": {
          \"name\": \"$CATALOG\",
          \"type\": \"INTERNAL\",
          \"properties\": {
            \"default-base-location\": \"s3://$BUCKET\",
            \"s3.endpoint\": \"$S3_ENDPOINT\",
            \"s3.region\": \"$S3_REGION\",
            \"s3.path-style-access\": \"false\",
            \"polaris.config.skip-credential-subscoping-indirection\": \"true\"
          },
          \"storageConfigInfo\": {
            \"storageType\": \"S3\",
            \"allowedLocations\": [\"s3://$BUCKET\", \"s3://$BUCKET/*\"],
            \"endpoint\": \"$S3_ENDPOINT\",
            \"pathStyleAccess\": false,
            \"region\": \"$S3_REGION\"
          }
        }
      }')
    cat /tmp/o; echo
    case \"\$code\" in
      200|201) echo 'catalog created' ;;
      409)     echo 'catalog already exists — ok' ;;
      *)       echo \"unexpected status \$code\" >&2; exit 1 ;;
    esac
  "
echo "==> catalog OK"
