#!/usr/bin/env bash
# Bootstrap Apache Polaris (ADR-0010). The upstream chart has no bootstrap job,
# so the two one-time steps live here:
#
#   schema   — polaris-admin-tool: create the metastore schema in the `polaris`
#              Postgres DB and the `ohdp` realm + its root principal. Must run
#              BEFORE the first `helm upgrade --install polaris` or the server
#              fails its readiness probe.
#   catalog  — create the INTERNAL catalog `ohdp` (warehouse root
#              s3://<bucket>, allowed locations under it) via the management API.
#              Must run AFTER the server is up. Idempotent — a 409 is fine.
#
# `make -C platform/helm polaris` runs `schema`, then helm, then `catalog`.
#
# Root principal credentials == the pipeline's OHDP_ICEBERG_CREDENTIAL
# ("<clientId>:<clientSecret>", ADR-0010). Pass it in the environment, or the
# script reads it from the `ohdp-pipeline-secrets` secret in `data`.
set -euo pipefail

: "${KUBECONFIG:?export KUBECONFIG first}"
cmd="${1:?usage: polaris-bootstrap.sh <schema|catalog>}"

NS=data
REALM=ohdp
CATALOG=ohdp
ADMIN_IMAGE="apache/polaris-admin-tool:${POLARIS_VERSION:-1.7.0}"
BUCKET="${OHDP_SPACES_BUCKET:-ohdp-warehouse}"
S3_ENDPOINT="${OHDP_SPACES_ENDPOINT_URL:-https://nyc3.digitaloceanspaces.com}"
S3_REGION="${OHDP_SPACES_REGION:-nyc3}"

cred="${OHDP_ICEBERG_CREDENTIAL:-}"
if [[ -z "$cred" ]]; then
  cred=$(kubectl -n "$NS" get secret ohdp-pipeline-secrets \
    -o jsonpath='{.data.OHDP_ICEBERG_CREDENTIAL}' 2>/dev/null | base64 -d || true)
fi
[[ -n "$cred" && "$cred" == *:* ]] || {
  echo "OHDP_ICEBERG_CREDENTIAL (<clientId>:<clientSecret>) not set and not found in ohdp-pipeline-secrets" >&2
  exit 1
}
CLIENT_ID="${cred%%:*}"
CLIENT_SECRET="${cred#*:}"

case "$cmd" in
schema)
  echo "==> polaris-admin-tool bootstrap: schema + realm '$REALM'"
  # The persistence secret is generated by platform-base; feed the same three
  # values to the admin tool as quarkus.datasource.* env.
  JDBC_URL=$(kubectl -n "$NS" get secret polaris-persistence -o jsonpath='{.data.jdbcUrl}' | base64 -d)
  DB_USER=$(kubectl -n "$NS" get secret polaris-persistence -o jsonpath='{.data.username}' | base64 -d)
  DB_PASS=$(kubectl -n "$NS" get secret polaris-persistence -o jsonpath='{.data.password}' | base64 -d)

  kubectl -n "$NS" delete pod polaris-bootstrap --ignore-not-found
  kubectl -n "$NS" run polaris-bootstrap --rm -i --restart=Never \
    --image="$ADMIN_IMAGE" \
    --env="polaris.persistence.type=relational-jdbc" \
    --env="quarkus.datasource.jdbc.url=$JDBC_URL" \
    --env="quarkus.datasource.username=$DB_USER" \
    --env="quarkus.datasource.password=$DB_PASS" \
    --command -- bootstrap -r "$REALM" -c "$REALM,$CLIENT_ID,$CLIENT_SECRET"
  echo "==> schema OK (re-runs are safe: bootstrap skips an already-bootstrapped realm)"
  ;;

catalog)
  echo "==> creating catalog '$CATALOG' via the management API"
  base="http://polaris.$NS.svc.cluster.local:8181"
  # Run curl+jq from a throwaway pod in-cluster so we hit the ClusterIP service.
  kubectl -n "$NS" run polaris-catalog-init --rm -i --restart=Never \
    --image=badouralix/curl-jq --quiet -- sh -euc "
      token=\$(curl -sf -X POST '$base/api/catalog/v1/oauth/tokens' \
        -d grant_type=client_credentials \
        -d client_id='$CLIENT_ID' -d client_secret='$CLIENT_SECRET' \
        -d scope='PRINCIPAL_ROLE:ALL' | jq -r .access_token)
      [ -n \"\$token\" ] && [ \"\$token\" != null ] || { echo 'token request failed' >&2; exit 1; }

      code=\$(curl -s -o /tmp/o -w '%{http_code}' -X POST '$base/api/management/v1/catalogs' \
        -H \"Authorization: Bearer \$token\" -H 'Content-Type: application/json' \
        -d '{
          \"catalog\": {
            \"name\": \"$CATALOG\",
            \"type\": \"INTERNAL\",
            \"properties\": {
              \"default-base-location\": \"s3://$BUCKET\",
              \"s3.endpoint\": \"$S3_ENDPOINT\",
              \"s3.region\": \"$S3_REGION\",
              \"s3.path-style-access\": \"false\",
              \"polaris.config.skip-credential-subscoping-indirection\": \"true\"
            },
            \"storageConfigInfo\": {
              \"storageType\": \"S3\",
              \"allowedLocations\": [\"s3://$BUCKET/*\"],
              \"endpoint\": \"$S3_ENDPOINT\",
              \"pathStyleAccess\": false,
              \"region\": \"$S3_REGION\"
            }
          }
        }')
      cat /tmp/o; echo
      case \"\$code\" in
        200|201) echo 'catalog created' ;;
        409)     echo 'catalog already exists — ok' ;;
        *)       echo \"unexpected status \$code\" >&2; exit 1 ;;
      esac
    "
  echo "==> catalog OK"
  ;;

*)
  echo "usage: polaris-bootstrap.sh <schema|catalog>" >&2
  exit 1
  ;;
esac
